# Generated by Django 3.2.11 on 2022-01-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
        ('label', '0001_initial'),
        ('branch', '0002_branch_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pullrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed'), ('Merged', 'Merged')], default='Opened', max_length=20)),
                ('created', models.DateField()),
                ('merge_date', models.DateField(blank=True, null=True)),
                ('labels', models.ManyToManyField(to='label.Label')),
                ('prRepository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.repository')),
                ('source_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_branch', to='branch.branch')),
                ('target_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_branch', to='branch.branch')),
            ],
        ),
    ]
