# Generated by Django 3.2.11 on 2022-01-24 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
                ('opened_by', models.CharField(default='', max_length=50)),
                ('assignee', models.ManyToManyField(blank=True, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, to='label.Label')),
            ],
        ),
    ]
